const crypto = require("crypto");
const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");

const { uploadDir } = require("./db");

/** Where uploaded files live. Local disk by default - the site has always
 * bind-mounted ./uploads off the Pi's SD card and that keeps working with
 * zero configuration.
 *
 * Set STORAGE_DRIVER=s3 (plus the S3_* vars) to put new uploads in an
 * S3-compatible bucket instead. Everything that touches a file goes through
 * this module, so that switch is the whole change - no route, template or
 * serializer knows which driver is active.
 *
 * Deliberately no AWS SDK: signing a PUT is ~40 lines of node:crypto, and
 * @aws-sdk/client-s3 would add tens of megabytes to an image that runs on a
 * Raspberry Pi. It also means any S3-compatible provider works - Cloudflare
 * R2, Backblaze B2, Hetzner, MinIO - not just AWS. */
const DRIVER = (process.env.STORAGE_DRIVER || "local").toLowerCase();

const S3 = {
  bucket: process.env.S3_BUCKET || "",
  region: process.env.S3_REGION || "auto",
  endpoint: (process.env.S3_ENDPOINT || "").replace(/\/$/, ""),
  accessKeyId: process.env.S3_ACCESS_KEY_ID || "",
  secretAccessKey: process.env.S3_SECRET_ACCESS_KEY || "",
  // Where the browser fetches objects from. Usually a CDN or bucket domain;
  // falls back to the API endpoint, which only works on public buckets.
  publicBaseUrl: (process.env.S3_PUBLIC_BASE_URL || "").replace(/\/$/, ""),
  prefix: (process.env.S3_PREFIX || "").replace(/^\/|\/$/g, "")
};

const MIME_BY_EXT = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".mp3": "audio/mpeg",
  ".m4a": "audio/mp4",
  ".ogg": "audio/ogg",
  ".wav": "audio/wav",
  ".weba": "audio/webm",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
  ".mov": "video/quicktime"
};

function s3Configured() {
  return Boolean(S3.bucket && S3.endpoint && S3.accessKeyId && S3.secretAccessKey);
}

/** True only when S3 is both selected AND fully configured. A half-configured
 * bucket falls back to local disk rather than taking the site down - the same
 * graceful-degradation rule the mail, donation and AI modules follow. */
const usingS3 = DRIVER === "s3" && s3Configured();

if (DRIVER === "s3" && !usingS3) {
  console.error("[storage] STORAGE_DRIVER=s3 but S3_BUCKET/S3_ENDPOINT/S3_ACCESS_KEY_ID/S3_SECRET_ACCESS_KEY are incomplete - falling back to local disk");
}

function describe() {
  if (!usingS3) return DRIVER === "s3" ? "local disk (S3 selected but misconfigured)" : "local disk";
  return `s3: ${S3.bucket} at ${S3.endpoint}${S3.prefix ? ` (prefix ${S3.prefix})` : ""}`;
}

function keyFor(filename) {
  return S3.prefix ? `${S3.prefix}/${filename}` : filename;
}

function contentTypeFor(filename) {
  return MIME_BY_EXT[path.extname(filename).toLowerCase()] || "application/octet-stream";
}

// --------------------------------------------------------------- SigV4 ---

function sha256hex(data) {
  return crypto.createHash("sha256").update(data).digest("hex");
}

function hmac(key, str) {
  return crypto.createHmac("sha256", key).update(str, "utf8").digest();
}

/** Minimal AWS Signature V4 for S3. Returns the headers to send.
 *
 * Only signs what this app actually issues: single-shot PUT/DELETE/GET with
 * no query string. Object keys are generated by lib/upload.js as
 * `<timestamp>-<hex><ext>`, so they never contain characters that need
 * URI escaping - the canonical path is used as-is. Anything that starts
 * accepting user-supplied keys must revisit that. */
function signedHeaders({ method, url, payload = "", contentType, extraHeaders = {}, now = new Date() }) {
  const u = new URL(url);
  const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, "");
  const dateStamp = amzDate.slice(0, 8);
  const payloadHash = sha256hex(payload);

  const headers = {
    host: u.host,
    "x-amz-content-sha256": payloadHash,
    "x-amz-date": amzDate,
    ...extraHeaders
  };
  if (contentType) headers["content-type"] = contentType;

  const names = Object.keys(headers).map((h) => h.toLowerCase()).sort();
  const canonicalHeaders = names.map((n) => {
    const value = Object.entries(headers).find(([k]) => k.toLowerCase() === n)[1];
    return `${n}:${String(value).trim().replace(/\s+/g, " ")}\n`;
  }).join("");
  const signedHeaderList = names.join(";");

  const canonicalRequest = [
    method,
    u.pathname,
    u.searchParams.toString(),
    canonicalHeaders,
    signedHeaderList,
    payloadHash
  ].join("\n");

  const scope = `${dateStamp}/${S3.region}/s3/aws4_request`;
  const stringToSign = ["AWS4-HMAC-SHA256", amzDate, scope, sha256hex(canonicalRequest)].join("\n");

  const kDate = hmac(`AWS4${S3.secretAccessKey}`, dateStamp);
  const kRegion = hmac(kDate, S3.region);
  const kService = hmac(kRegion, "s3");
  const kSigning = hmac(kService, "aws4_request");
  const signature = crypto.createHmac("sha256", kSigning).update(stringToSign, "utf8").digest("hex");

  return {
    ...headers,
    Authorization: `AWS4-HMAC-SHA256 Credential=${S3.accessKeyId}/${scope}, SignedHeaders=${signedHeaderList}, Signature=${signature}`
  };
}

function objectUrl(filename) {
  return `${S3.endpoint}/${S3.bucket}/${keyFor(filename)}`;
}

async function s3Put(filename, body) {
  const contentType = contentTypeFor(filename);
  const url = objectUrl(filename);
  const res = await fetch(url, {
    method: "PUT",
    headers: signedHeaders({ method: "PUT", url, payload: body, contentType }),
    body
  });
  if (!res.ok) {
    throw new Error(`S3 PUT ${res.status}: ${(await res.text()).slice(0, 200)}`);
  }
}

async function s3Delete(filename) {
  const url = objectUrl(filename);
  const res = await fetch(url, {
    method: "DELETE",
    headers: signedHeaders({ method: "DELETE", url })
  });
  // 404 is fine - the goal is "it's gone", and it already is.
  if (!res.ok && res.status !== 404) {
    throw new Error(`S3 DELETE ${res.status}: ${(await res.text()).slice(0, 200)}`);
  }
}

// ------------------------------------------------------------- public API ---

/** The URL a browser or app should fetch this file from.
 *
 * `origin` is only used by the local driver, which serves files off this
 * same host - S3 URLs are absolute and origin-independent. */
function publicUrl(filename, origin = "") {
  if (!filename) return null;
  if (usingS3) {
    const base = S3.publicBaseUrl || `${S3.endpoint}/${S3.bucket}`;
    return `${base}/${keyFor(filename)}`;
  }
  return `${origin}/uploads/${encodeURIComponent(filename)}`;
}

/** Moves a freshly-uploaded temp file into permanent storage.
 *
 * multer always writes to local disk first (streaming straight to S3 would
 * mean chunked signing for a file we have to buffer anyway). On the local
 * driver the file is already where it belongs and this is a no-op; on S3 it
 * gets pushed up and the local copy removed.
 *
 * Throws on a failed upload rather than swallowing it - a post row pointing
 * at an object that isn't there is worse than a failed upload the user can
 * retry. Callers are expected to clean up the temp file on throw. */
async function commit(file) {
  if (!usingS3 || !file) return file?.filename || null;

  // Whole-file buffer: capped by multer at 8MB (images) or 64MB (media).
  // Fine for those sizes; revisit if the media ceiling ever goes up.
  const body = await fsp.readFile(file.path);
  await s3Put(file.filename, body);
  await fsp.rm(file.path, { force: true });
  return file.filename;
}

/** Deletes a stored file. Never throws - removal is always a side effect of
 * some other action (deleting a post, cleaning up a rejected upload), and a
 * storage hiccup must not fail that action or leave a half-deleted post. */
async function remove(filename) {
  if (!filename) return;
  try {
    if (usingS3) await s3Delete(filename);
    else await fsp.rm(path.join(uploadDir, filename), { force: true });
  } catch (err) {
    console.error(`[storage] failed to delete ${filename}: ${err.message}`);
  }
}

/** Synchronous local-only cleanup for the temp file on a rejected upload.
 * Used on paths that reject before commit(), where the file is still on
 * local disk regardless of driver. */
function discardTemp(file) {
  if (file?.path) fs.rmSync(file.path, { force: true });
}

module.exports = {
  publicUrl,
  commit,
  remove,
  discardTemp,
  describe,
  isRemote: () => usingS3,
  // exported for the migration script and the signer's test
  _internal: { signedHeaders, s3Put, keyFor, s3Configured, S3 }
};
